/*
 * gtest.cpp
 *
 *  Created on: Nov 12, 2013
 *      Author: arau
 */

#include "toys/sdl.h"
#include <sstream>


int main(int argc, char** argv) {
	using namespace toys;
	using namespace toys::sdl;
	using namespace toys::sdl::vals;
	sdltoys i;
	font f("/usr/share/fonts/truetype/freefont/FreeMono.ttf", 20);

	const rgba black{0, 0, 0, 0}; // this is constant
	rgba c{100, 100, 0, 0};    	  // this is used by reference
	auto rgbtxt = prop([&c]() {		  // this is property generated by lambda
		std::ostringstream buf;
		buf<<"r:"<<int(c.r)<<",g:"<<int(c.g)<<",b:"<<int(c.b);
		return buf.str();
	});

	auto moreblue = on_click([&c](click&){c.b+=25; },
				             fb(lay(mid, tx("more blue", f, black)), rc(rgba{200,200,250,0})));
	auto text = lay(mid, tx(rgbtxt, f, black));
	auto quit = on_click([](click&){ system::exit(0); },
						 fb(lay(mid, tx("exit", f, black)), rc(rgba{200, 200, 200,0})));

	auto z = fb(ud(0.33, text,
					     ud(0.5, lay(mid, sz(xy(0.5, 0.5), moreblue)),
								 lay(mid, sz(xy(0.5, 0.5), quit)))),
				rc(std::ref(c)));

	printf("toy size is %lu B\n", sizeof(z));

	window<decltype(z)&> wnd("foo", vec(), {400, 400}, z);
	return i.run(&wnd);
}
