/*
 * gtest.cpp
 *
 *  Created on: Nov 12, 2013
 *      Author: arau
 */

#include "toys/sdl.h"
#include <sstream>

using namespace std;
using namespace toys;
using namespace toys::sdl;
using namespace toys::sdl::vals;

unique_ptr<itoy> make_radio_button(const font& f, const function<void (bool)>& changed);
unique_ptr<itoy> make_resizing_item();

int main(int argc, char** argv) {
	sdltoys i;
	font f("/usr/share/fonts/truetype/freefont/FreeMono.ttf", 20);

	const rgba black{0, 0, 0, 0}; // this is constant
	rgba c{100, 100, 100, 0};    	  // this is used by reference
	auto rgbtxt = prop([&c]() {		  // this is property generated by lambda
		std::ostringstream buf;
		buf<<"r:"<<int(c.r)<<",g:"<<int(c.g)<<",b:"<<int(c.b);
		return buf.str();
	});

	auto radio = make_radio_button(f, [&c](bool v) { c.g = (v?200:100); });
	auto titledradio = lr(0.5, lay(mid, tx("green:", f, black)), lay(mid, radio.get()));

    auto resizing = make_resizing_item();

	auto text = lay(mid, tx(rgbtxt, f, black));
	auto moreblue = on_click([&c](click&){c.b+=32; },
				             fb(lay(mid, tx("more blue", f, black)), rc(rgba{200,200,250,0})));
	auto quit = on_click([](click&){ system::exit(0); },
						 fb(lay(mid, tx("exit", f, black)), rc(rgba{200, 200, 200,0})));

	auto z = fb(ud(0.33,
			       text,
 			       ud(0.5,
 			    	  lr(0.5, titledradio, lay(mid, resizing.get())),
					  lr(0.5, lay(mid, sz(xy(0.67, 0.5), moreblue)),
						      lay(mid, sz(xy(0.67, 0.5), quit))))),
				rc(std::ref(c)));

	printf("quit size is %lu B\n", sizeof(quit));
	printf("toy size is %lu B\n", sizeof(z));

	window<decltype(z)&> wnd("foo", vec(), {400, 400}, z);
	return i.run(&wnd);
}
